### ISSUE TITLE
Elastica Library updation

### ISSUE THREAD

**Issue by dextar1** [DMKEBUSINESSGMBH/typo3-mksearch#29]
Hi,
If there is someone working to update Elastica Library?

**Comment by hannesbochmann** [comment]
No, I think there is nobody.

**Comment by dextar1** [comment]
i have made some minor changes in Status.php of Elastica Library to make it work with the latest Elastic Search. if i give you Pull Request of that. would you accept that?

**Comment by hannesbochmann** [comment]
Please don't change the currently included Elastica library. This way we won't be update-safe. Instead try to include the current Elastica library to make it work.

**Comment by dextar1** [comment]
ok i need bit of your help. new Elastica library needs Psr\Log and Elasticsearch Libraries. i updated Elastica in lib folder and then placed 2 libraries in the same folder lib. and path is also fine with namespace like in lib folder there is Psr\Log\NullLogger class but it still gives me error Class 'Psr\\Log\\NullLogger' not found in mksearch/lib/Elastica/Client.php

**Comment by hannesbochmann** [comment]
Take a look [here](https://github.com/DMKEBUSINESSGMBH/typo3-mksearch/blob/master/service/engine/class.tx_mksearch_service_engine_ElasticSearch.php#L79-L90). The autoloading is only implemented for classes with "Elastica" in it. I think that's why it won't work.

The autoloading of Elastica needs to be implemented differently I think. The best would be to use composer autoloading but this will only work since TYPO3 7.6. Another downside is that you would need to add Elastica as dependency for mksearch. This way you could only use ElasticSearch with mksearch if the project is built through composer. Nevertheless you should give it a try (you need to take care that Elastica is installed into the correct path -> /lib).

**Comment by dextar1** [comment]
yes i edited that code and now it loads properly Psr and Elasticsearch, now checking alternatives of deprecated functions

**Comment by dextar1** [comment]
pull request sent.

**Comment by hannesbochmann** [comment]
Is this version of Elastica backwards compatible to older ElasticSearch versions?

**Comment by hannesbochmann** [comment]
Thank you very much-
Is this version of Elastica backwards compatible to older ElasticSearch versions?

**Comment by dextar1** [comment]
this is not tested. but i dont have older ver of elastic search installed on my VM. can you do that if you have older ver of elastic search?

**Comment by hannesbochmann** [comment]
Seems like the newest version only supports ElasticSearch 5.x. The initial development was done with ElasticSearch 1.4.0. It would be great to have the possiblity to use different versions of ElasticSearch/Elastica. 
But I guess this would mean some more changes to the code.
